const $=s=>document.querySelector(s), feed=$('#feed'), empty=$('#empty'), phase=$('#phase strong');
const names={
  ja:'日本語',en:'English',ko:'한국어',zh:'中文',es:'Español',fr:'Français',de:'Deutsch',it:'Italiano',pt:'Português',ru:'Русский',
  ar:'العربية',hi:'हिन्दी',vi:'Tiếng Việt',th:'ไทย',id:'Bahasa Indonesia',ms:'Bahasa Melayu',tr:'Türkçe',nl:'Nederlands',pl:'Polski',uk:'Українська',cs:'Čeština',he:'עברית'
};
const messages={
  ko:{subtitle:'실시간 로컬 통역 · 온라인 신경망 음성',uiLanguage:'화면 언어',connecting:'연결 중',connected:'로컬 연결됨',reconnecting:'재연결 중',runtime:'실행 상태',starting:'시작 중',detectedLanguage:'현재 고객 언어',privacy:'처리 방식',processing:'실시간 STT·번역은 이 PC · 음성은 온라인',pause:'일시 정지',resume:'다시 시작',channelSettings:'번역 및 언어 설정',allLanguages:'지원 언어 전체 사용 가능',inputLanguage:'고객 입력 언어',inputDevice:'음성 입력 장치',outputDevice:'음성 출력 장치',systemDefault:'시스템 기본 장치',customerSpeech:'고객 음성',japaneseText:'일본어 텍스트',japaneseReply:'일본어 답변',customerTts:'고객 언어 음성',speechMode:'인식 모드',staffSpeech:'직원 말하기 · Space 누르는 동안',staffSpeechActive:'직원 말하기 · 일본어 고정',ttsOn:'TTS 켜짐',ttsOff:'TTS 꺼짐',edgeNote:'말하는 중에는 임시 자막을 먼저 표시하고, 문장이 끝나면 정확한 결과와 번역으로 교체합니다.',output:'실시간 통역 출력',outputHint:'임시 자막은 최종 결과로 자동 교체됩니다',loadingTitle:'모델을 준비하고 있습니다',loadingBody:'준비가 끝나면 고객 음성을 듣기 시작합니다.',incoming:'고객 · 일본어 번역',reply:'직원 · 고객 언어 음성',clearHistory:'기록 지우기',historyCleared:'화면 기록을 지웠습니다',correct:'교정 기록',correctSource:'인식된 원문을 수정하세요',correctTranslation:'번역문을 수정하세요',saved:'교정을 로컬에 저장했습니다',liveCaption:'실시간 인식 중',awaitingTranslation:'최종 인식 및 번역 준비 중',statusLoading:'모델 준비 중',statusListening:'듣는 중',statusRecognizing:'최종 음성 인식 중',statusTranslating:'번역 중',statusSpeaking:'번역 음성 재생 중',statusPaused:'일시 정지됨',statusWarning:'주의',statusError:'오류'},
  ja:{subtitle:'リアルタイム・ローカル通訳・オンライン音声',uiLanguage:'表示言語',connecting:'接続中',connected:'ローカル接続済み',reconnecting:'再接続中',runtime:'実行状態',starting:'起動中',detectedLanguage:'現在のお客様言語',privacy:'処理方式',processing:'リアルタイム認識・翻訳はこのPC・音声はオンライン',pause:'一時停止',resume:'再開',channelSettings:'翻訳・言語設定',allLanguages:'対応言語をすべて選択可能',inputLanguage:'お客様の入力言語',inputDevice:'音声入力デバイス',outputDevice:'音声出力デバイス',systemDefault:'システム既定',customerSpeech:'お客様の音声',japaneseText:'日本語テキスト',japaneseReply:'日本語の返答',customerTts:'お客様言語の音声',speechMode:'認識モード',staffSpeech:'スタッフ発話・Spaceを押している間',staffSpeechActive:'スタッフ発話・日本語固定',ttsOn:'TTS オン',ttsOff:'TTS オフ',edgeNote:'話している間は暫定字幕を表示し、発話終了後に最終認識・翻訳へ置き換えます。',output:'リアルタイム通訳出力',outputHint:'暫定字幕は最終結果で自動更新されます',loadingTitle:'モデルを準備しています',loadingBody:'準備が完了するとお客様の音声を聞き始めます。',incoming:'お客様・日本語訳',reply:'スタッフ・お客様言語音声',clearHistory:'履歴を消去',historyCleared:'表示履歴を消去しました',correct:'訂正を記録',correctSource:'認識された原文を修正してください',correctTranslation:'翻訳文を修正してください',saved:'訂正をローカルに保存しました',liveCaption:'リアルタイム認識中',awaitingTranslation:'最終認識・翻訳を準備中',statusLoading:'モデルを準備中',statusListening:'聞き取り中',statusRecognizing:'最終音声認識中',statusTranslating:'翻訳中',statusSpeaking:'翻訳音声を再生中',statusPaused:'一時停止中',statusWarning:'注意',statusError:'エラー'},
  en:{subtitle:'Real-time local interpreter · online neural voice',uiLanguage:'UI language',connecting:'Connecting',connected:'Local connection',reconnecting:'Reconnecting',runtime:'Runtime',starting:'Starting',detectedLanguage:'Customer language',privacy:'Processing',processing:'Live STT and translation on this PC · voice online',pause:'Pause',resume:'Resume',channelSettings:'Translation and language settings',allLanguages:'All supported languages are available',inputLanguage:'Customer input language',inputDevice:'Audio input device',outputDevice:'Audio output device',systemDefault:'System default',customerSpeech:'Customer speech',japaneseText:'Japanese text',japaneseReply:'Japanese reply',customerTts:'Customer-language audio',speechMode:'Recognition mode',staffSpeech:'Staff speaking · hold Space',staffSpeechActive:'Staff speaking · Japanese fixed',ttsOn:'TTS on',ttsOff:'TTS off',edgeNote:'A live caption appears while speech continues, then is replaced by final recognition and translation.',output:'Real-time interpretation output',outputHint:'Live captions are automatically replaced by final results',loadingTitle:'Preparing local models',loadingBody:'Listening starts when the models are ready.',incoming:'Customer · Japanese translation',reply:'Staff · customer-language voice',clearHistory:'Clear history',historyCleared:'Display history cleared',correct:'Record correction',correctSource:'Correct the recognized text',correctTranslation:'Correct the translation',saved:'Correction saved locally',liveCaption:'Live recognition',awaitingTranslation:'Preparing final recognition and translation',statusLoading:'Preparing models',statusListening:'Listening',statusRecognizing:'Final speech recognition',statusTranslating:'Translating',statusSpeaking:'Playing translated voice',statusPaused:'Paused',statusWarning:'Warning',statusError:'Error'},
  zh:{subtitle:'实时本地口译 · 在线神经语音',uiLanguage:'界面语言',connecting:'连接中',connected:'本地已连接',reconnecting:'正在重连',runtime:'运行状态',starting:'启动中',detectedLanguage:'当前客人语言',privacy:'处理方式',processing:'实时识别和翻译在本机 · 语音在线',pause:'暂停',resume:'继续',channelSettings:'翻译与语言设置',allLanguages:'可直接选择所有支持的语言',inputLanguage:'客人输入语言',inputDevice:'音频输入设备',outputDevice:'音频输出设备',systemDefault:'系统默认设备',customerSpeech:'客人语音',japaneseText:'日语文本',japaneseReply:'日语回复',customerTts:'客人语言语音',speechMode:'识别模式',staffSpeech:'员工发言 · 按住 Space',staffSpeechActive:'员工发言 · 固定日语',ttsOn:'TTS 开启',ttsOff:'TTS 关闭',edgeNote:'说话过程中先显示临时字幕，结束后自动替换为最终识别和翻译。',output:'实时口译输出',outputHint:'临时字幕会自动替换为最终结果',loadingTitle:'正在准备本地模型',loadingBody:'准备完成后开始接收客人语音。',incoming:'客人 · 日语翻译',reply:'员工 · 客人语言语音',clearHistory:'清除记录',historyCleared:'显示记录已清除',correct:'保存更正',correctSource:'请更正识别的文本',correctTranslation:'请更正译文',saved:'更正已保存在本机',liveCaption:'实时识别中',awaitingTranslation:'正在准备最终识别和翻译',statusLoading:'正在准备模型',statusListening:'正在聆听',statusRecognizing:'最终语音识别中',statusTranslating:'正在翻译',statusSpeaking:'正在播放译文语音',statusPaused:'已暂停',statusWarning:'警告',statusError:'错误'},
  es:{subtitle:'Intérprete local en tiempo real · voz neuronal en línea',uiLanguage:'Idioma de interfaz',connecting:'Conectando',connected:'Conexión local',reconnecting:'Reconectando',runtime:'Estado de ejecución',starting:'Iniciando',detectedLanguage:'Idioma del cliente',privacy:'Procesamiento',processing:'STT en vivo y traducción en este PC · voz en línea',pause:'Pausar',resume:'Continuar',channelSettings:'Traducción e idioma',allLanguages:'Todos los idiomas compatibles están disponibles',inputLanguage:'Idioma del cliente',inputDevice:'Dispositivo de entrada',outputDevice:'Dispositivo de salida',systemDefault:'Dispositivo predeterminado',customerSpeech:'Voz del cliente',japaneseText:'Texto japonés',japaneseReply:'Respuesta en japonés',customerTts:'Voz en idioma del cliente',speechMode:'Modo de reconocimiento',staffSpeech:'Personal habla · mantenga Space',staffSpeechActive:'Personal habla · japonés fijo',ttsOn:'TTS activado',ttsOff:'TTS desactivado',edgeNote:'Mientras se habla aparece un subtítulo temporal y al terminar se sustituye por el reconocimiento y la traducción finales.',output:'Salida de interpretación en tiempo real',outputHint:'Los subtítulos temporales se sustituyen automáticamente',loadingTitle:'Preparando modelos locales',loadingBody:'La escucha comenzará cuando los modelos estén listos.',incoming:'Cliente · traducción japonesa',reply:'Personal · voz en idioma del cliente',clearHistory:'Borrar historial',historyCleared:'Historial borrado',correct:'Guardar corrección',correctSource:'Corrige el texto reconocido',correctTranslation:'Corrige la traducción',saved:'Corrección guardada localmente',liveCaption:'Reconocimiento en vivo',awaitingTranslation:'Preparando reconocimiento y traducción finales',statusLoading:'Preparando modelos',statusListening:'Escuchando',statusRecognizing:'Reconocimiento final',statusTranslating:'Traduciendo',statusSpeaking:'Reproduciendo voz traducida',statusPaused:'En pausa',statusWarning:'Aviso',statusError:'Error'}
};
let ui=localStorage.getItem('remoteplus-ui-language')||'ko',state={tts_enabled:true,paused:false,speech_mode:'customer'},retry=700,toastTimer,missingInput=0;
const cards=new Map();
const t=key=>messages[ui]?.[key]||messages.en[key]||key;
const phaseKey={starting:'starting',loading:'statusLoading',listening:'statusListening',recognizing:'statusRecognizing',translating:'statusTranslating',speaking:'statusSpeaking',paused:'statusPaused',warning:'statusWarning',error:'statusError'};
function applyI18n(){document.documentElement.lang=ui;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));$('#ui-language').value=ui;applyState(state);for(const card of cards.values()){const label=card.querySelector('.meta b');if(card.dataset.live==='1')label.textContent=t('liveCaption');else label.textContent=card.dataset.direction==='reply'?t('reply'):t('incoming')}}
function toast(message){if(!message)return;const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),4200)}
function status(data){phase.textContent=t(phaseKey[data.phase]||'starting');$('.pulse').style.background=data.phase==='error'?'var(--red)':data.phase==='warning'?'#db9b3b':'var(--green)'}
function setPartner(code){$('#partner').textContent=names[code]||code?.toUpperCase()||'-'}
function selectValue(id,value){const el=$(id),wanted=String(value);if([...el.options].some(x=>x.value===wanted))el.value=wanted}
function makeCard(id,direction='incoming'){empty?.remove();const el=document.createElement('article');el.className='entry '+(direction==='reply'?'reply':'incoming');el.dataset.id=String(id);el.dataset.direction=direction;const meta=document.createElement('div');meta.className='meta';const label=document.createElement('b');const tools=document.createElement('span');const timing=document.createElement('span');timing.className='timing';const correction=document.createElement('button');correction.className='correction';correction.textContent=t('correct');correction.hidden=true;tools.append(timing,correction);meta.append(label,tools);const main=document.createElement('div');main.className='main';const source=document.createElement('div');source.className='source';el.append(meta,main,source);feed.appendChild(el);cards.set(String(id),el);while(feed.children.length>20){const first=feed.firstChild;if(first?.dataset?.id)cards.delete(first.dataset.id);feed.removeChild(first)}return el}
function setCardTiming(el,value){el.querySelector('.timing').textContent=value||''}
function preview(item){const d=item.data||item;if(!d.text)return;const id=String(d.utterance_id);let el=cards.get(id);if(!el)el=makeCard(id,d.speech_mode==='staff'?'reply':'incoming');if(el.dataset.final==='1')return;el.classList.add('live');el.dataset.live='1';el.querySelector('.meta b').textContent=t('liveCaption');el.querySelector('.main').textContent=t('awaitingTranslation');el.querySelector('.source').textContent=d.text;setCardTiming(el,'LIVE');if(d.language)setPartner(d.language);el.scrollIntoView({behavior:'smooth',block:'end'})}
function discardPreview(item){const d=item.data||item,id=String(d.utterance_id),el=cards.get(id);if(el&&el.dataset.final!=='1'){cards.delete(id);el.remove()}}
function add(item){const d=item.data||item;if(d.direction===undefined)return;const id=String(d.utterance_id||`final-${Date.now()}-${Math.random()}`);let el=cards.get(id);if(!el)el=makeCard(id,d.direction);el.className='entry '+(d.direction==='reply'?'reply':'incoming');el.dataset.direction=d.direction;el.dataset.final='1';el.dataset.live='0';el.querySelector('.meta b').textContent=d.direction==='reply'?t('reply'):t('incoming');setCardTiming(el,d.latency_seconds?`${d.latency_seconds}s`:'');el.querySelector('.main').textContent=d.translated;el.querySelector('.source').textContent=d.source;const correction=el.querySelector('.correction');correction.hidden=false;correction.onclick=()=>saveCorrection(d).catch(e=>toast(e.message));if(d.source_language)setPartner(d.source_language);el.scrollIntoView({behavior:'smooth',block:'end'})}
async function saveCorrection(d){const correctedSource=prompt(t('correctSource'),d.source);if(correctedSource===null)return;const correctedTranslation=prompt(t('correctTranslation'),d.translated);if(correctedTranslation===null)return;if(correctedSource===d.source&&correctedTranslation===d.translated)return;const r=await fetch('/api/feedback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({direction:d.direction,source_language:d.source_language,source:d.source,translation:d.translated,corrected_source:correctedSource===d.source?'':correctedSource,corrected_translation:correctedTranslation===d.translated?'':correctedTranslation})});if(!r.ok)throw Error((await r.json()).detail||'Unable to save correction');toast(t('saved'))}
function applyState(next){state={...state,...next};$('#tts').classList.toggle('on',!!state.tts_enabled);$('#tts').setAttribute('aria-pressed',!!state.tts_enabled);$('#tts em').textContent=state.tts_enabled?t('ttsOn'):t('ttsOff');$('#pause').textContent=state.paused?t('resume'):t('pause');if(state.input_language&&$('#language').options.length)selectValue('#language',state.input_language);if(state.input_device!==undefined&&$('#input-device').options.length)selectValue('#input-device',state.input_device);if(state.output_device!==undefined&&$('#output-device').options.length)selectValue('#output-device',state.output_device);const staff=state.speech_mode==='staff',mode=$('#speech-mode');mode.classList.toggle('staff',staff);mode.setAttribute('aria-pressed',String(staff));mode.querySelector('em').textContent=staff?t('staffSpeechActive'):t('staffSpeech');if(state.input_language)setPartner(state.input_language)}
function renderLanguages(languages){const input=$('#language'),chosen=state.input_language;input.replaceChildren();for(const lang of languages){const op=document.createElement('option');op.value=lang.code;op.textContent=`${lang.native_name} (${lang.name})`;input.appendChild(op)}selectValue('#language',chosen)}
async function loadDevices(){const r=await fetch('/api/devices');if(!r.ok)throw Error((await r.json()).detail||'Could not load devices');const d=await r.json(),input=$('#input-device'),output=$('#output-device'),chosenInput=state.input_device,chosenOutput=state.output_device;for(const [select,items,chosen] of [[input,d.inputs||[],chosenInput],[output,d.outputs||[],chosenOutput]]){select.replaceChildren();const def=document.createElement('option');def.value='default';def.textContent=t('systemDefault');select.appendChild(def);for(const item of items){const op=document.createElement('option');op.value=item.id;op.textContent=item.name;select.appendChild(op)}selectValue('#'+select.id,chosen)}if(d.warnings?.length&&!missingInput++){toast(d.warnings[0])}}
async function control(payload){const r=await fetch('/api/control',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw Error((await r.json()).detail||'Control update failed');applyState(await r.json())}
function clearFeed(){cards.clear();feed.replaceChildren(empty)}
function snapshot(data){clearFeed();applyState(data.state);status(data.state);renderLanguages(data.languages);for(const ev of data.history||[])if(ev.type==='translation')add(ev)}
$('#language').onchange=e=>control({active_language:e.target.value}).catch(err=>toast(err.message));$('#input-device').onchange=e=>control({input_device:e.target.value}).catch(err=>toast(err.message));$('#output-device').onchange=e=>control({output_device:e.target.value}).catch(err=>toast(err.message));$('#tts').onclick=()=>control({tts_enabled:!state.tts_enabled}).catch(err=>toast(err.message));$('#pause').onclick=()=>control({paused:!state.paused}).catch(err=>toast(err.message));
function setStaff(active){if((state.speech_mode==='staff')===active)return;control({speech_mode:active?'staff':'customer'}).catch(err=>toast(err.message))}
const mode=$('#speech-mode');mode.addEventListener('pointerdown',e=>{e.preventDefault();setStaff(true)});for(const event of ['pointerup','pointercancel','pointerleave'])mode.addEventListener(event,()=>setStaff(false));window.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&document.activeElement?.tagName!=='SELECT'){e.preventDefault();setStaff(true)}});window.addEventListener('keyup',e=>{if(e.code==='Space'){e.preventDefault();setStaff(false)}});window.addEventListener('blur',()=>setStaff(false));
$('#clear-history').onclick=()=>{if(confirm(t('clearHistory')+'?'))fetch('/api/history',{method:'DELETE'}).then(r=>{if(!r.ok)throw Error('Unable to clear history');clearFeed()}).catch(e=>toast(e.message))};$('#ui-language').onchange=e=>{ui=e.target.value;localStorage.setItem('remoteplus-ui-language',ui);applyI18n()};
function connect(){const protocol=location.protocol==='https:'?'wss':'ws',ws=new WebSocket(`${protocol}://${location.host}/ws`);ws.onopen=()=>{$('#connection').classList.add('on');$('#connection span').textContent=t('connected');retry=700};ws.onclose=()=>{$('#connection').classList.remove('on');$('#connection span').textContent=t('reconnecting');setTimeout(connect,retry);retry=Math.min(retry*1.7,8000)};ws.onmessage=e=>{const event=JSON.parse(e.data);if(event.type==='snapshot')snapshot(event.data);else if(event.type==='preview')preview(event);else if(event.type==='preview_discard')discardPreview(event);else if(event.type==='translation')add(event);else if(event.type==='status')status(event.data);else if(event.type==='state')applyState(event.data);else if(event.type==='history_cleared')clearFeed();else if(event.type==='error'||event.type==='warning')toast(event.data.message)}}
applyI18n();loadDevices().catch(error=>toast(error.message));setInterval(()=>loadDevices().catch(()=>{}),10000);connect();
