const $=s=>document.querySelector(s), feed=$('#feed'), empty=$('#empty'), phase=$('#phase strong');
const names={
  ja:'日本語',en:'English',ko:'한국어',zh:'中文',es:'Español',fr:'Français',de:'Deutsch',it:'Italiano',pt:'Português',ru:'Русский',
  ar:'العربية',hi:'हिन्दी',vi:'Tiếng Việt',th:'ไทย',id:'Bahasa Indonesia',ms:'Bahasa Melayu',tr:'Türkçe',nl:'Nederlands',pl:'Polski',uk:'Українська',cs:'Čeština',he:'עברית'
};
const messages={
  ko:{subtitle:'로컬 통역 · 온라인 신경망 음성',uiLanguage:'화면 언어',connecting:'연결 중',connected:'로컬 연결됨',reconnecting:'재연결 중',runtime:'실행 상태',starting:'시작 중',detectedLanguage:'현재 고객 언어',privacy:'처리 방식',processing:'STT·번역은 이 PC · 음성은 온라인',pause:'일시 정지',resume:'다시 시작',channelSettings:'번역 및 언어 설정',allLanguages:'지원 언어 전체 사용 가능',inputLanguage:'고객 입력 언어',inputDevice:'음성 입력 장치',systemDefault:'시스템 기본 장치',customerSpeech:'고객 음성',japaneseText:'일본어 텍스트',japaneseReply:'일본어 답변',customerTts:'고객 언어 음성',speechMode:'인식 모드',staffSpeech:'직원 말하기 · Space 누르는 동안',staffSpeechActive:'직원 말하기 · 일본어 고정',ttsOn:'TTS 켜짐',ttsOff:'TTS 꺼짐',edgeNote:'온라인 신경망 음성을 사용합니다. Windows 음성 언어팩은 필요하지 않습니다.',output:'통합 번역 출력',outputHint:'원문과 일본어를 함께 표시합니다',loadingTitle:'모델을 준비하고 있습니다',loadingBody:'준비가 끝나면 고객 음성을 듣기 시작합니다.',incoming:'고객 · 일본어 번역',reply:'직원 · 고객 언어 음성',clearHistory:'기록 지우기',historyCleared:'화면 기록을 지웠습니다',correct:'교정 기록',correctSource:'인식된 원문을 수정하세요',correctTranslation:'번역문을 수정하세요',saved:'교정을 로컬에 저장했습니다'},
  ja:{subtitle:'ローカル通訳・オンライン音声',uiLanguage:'表示言語',connecting:'接続中',connected:'ローカル接続済み',reconnecting:'再接続中',runtime:'実行状態',starting:'起動中',detectedLanguage:'現在のお客様言語',privacy:'処理方式',processing:'音声認識・翻訳はこのPC・音声はオンライン',pause:'一時停止',resume:'再開',channelSettings:'翻訳・言語設定',allLanguages:'対応言語をすべて選択可能',inputLanguage:'お客様の入力言語',inputDevice:'音声入力デバイス',systemDefault:'システム既定',customerSpeech:'お客様の音声',japaneseText:'日本語テキスト',japaneseReply:'日本語の返答',customerTts:'お客様言語の音声',speechMode:'認識モード',staffSpeech:'スタッフ発話・Spaceを押している間',staffSpeechActive:'スタッフ発話・日本語固定',ttsOn:'TTS オン',ttsOff:'TTS オフ',edgeNote:'オンライン音声を使用します。Windows 音声言語パックは不要です。',output:'統合翻訳出力',outputHint:'原文と日本語を一緒に表示します',loadingTitle:'モデルを準備しています',loadingBody:'準備が完了するとお客様の音声を聞き始めます。',incoming:'お客様・日本語訳',reply:'スタッフ・お客様言語音声',clearHistory:'履歴を消去',historyCleared:'表示履歴を消去しました',correct:'訂正を記録',correctSource:'認識された原文を修正してください',correctTranslation:'翻訳文を修正してください',saved:'訂正をローカルに保存しました'},
  en:{subtitle:'Local interpreter · online neural voice',uiLanguage:'UI language',connecting:'Connecting',connected:'Local connection',reconnecting:'Reconnecting',runtime:'Runtime',starting:'Starting',detectedLanguage:'Customer language',privacy:'Processing',processing:'STT and translation on this PC · voice online',pause:'Pause',resume:'Resume',channelSettings:'Translation and language settings',allLanguages:'All supported languages are available',inputLanguage:'Customer input language',inputDevice:'Audio input device',systemDefault:'System default',customerSpeech:'Customer speech',japaneseText:'Japanese text',japaneseReply:'Japanese reply',customerTts:'Customer-language audio',speechMode:'Recognition mode',staffSpeech:'Staff speaking · hold Space',staffSpeechActive:'Staff speaking · Japanese fixed',ttsOn:'TTS on',ttsOff:'TTS off',edgeNote:'Online neural voices are used. Windows speech language packs are not required.',output:'Unified translation output',outputHint:'Shows the original and Japanese together',loadingTitle:'Preparing local models',loadingBody:'Listening starts when the models are ready.',incoming:'Customer · Japanese translation',reply:'Staff · customer-language voice',clearHistory:'Clear history',historyCleared:'Display history cleared',correct:'Record correction',correctSource:'Correct the recognized text',correctTranslation:'Correct the translation',saved:'Correction saved locally'},
  zh:{subtitle:'本地口译 · 在线神经语音',uiLanguage:'界面语言',connecting:'连接中',connected:'本地已连接',reconnecting:'正在重连',runtime:'运行状态',starting:'启动中',detectedLanguage:'当前客人语言',privacy:'处理方式',processing:'识别和翻译在本机 · 语音在线',pause:'暂停',resume:'继续',channelSettings:'翻译与语言设置',allLanguages:'可直接选择所有支持的语言',inputLanguage:'客人输入语言',inputDevice:'音频输入设备',systemDefault:'系统默认设备',customerSpeech:'客人语音',japaneseText:'日语文本',japaneseReply:'日语回复',customerTts:'客人语言语音',speechMode:'识别模式',staffSpeech:'员工发言 · 按住 Space',staffSpeechActive:'员工发言 · 固定日语',ttsOn:'TTS 开启',ttsOff:'TTS 关闭',edgeNote:'使用在线神经语音，无需 Windows 语音语言包。',output:'综合翻译输出',outputHint:'同时显示原文和日语',loadingTitle:'正在准备本地模型',loadingBody:'准备完成后开始接收客人语音。',incoming:'客人 · 日语翻译',reply:'员工 · 客人语言语音',clearHistory:'清除记录',historyCleared:'显示记录已清除',correct:'保存更正',correctSource:'请更正识别的文本',correctTranslation:'请更正译文',saved:'更正已保存在本机'},
  es:{subtitle:'Intérprete local · voz neuronal en línea',uiLanguage:'Idioma de interfaz',connecting:'Conectando',connected:'Conexión local',reconnecting:'Reconectando',runtime:'Estado de ejecución',starting:'Iniciando',detectedLanguage:'Idioma del cliente',privacy:'Procesamiento',processing:'STT y traducción en este PC · voz en línea',pause:'Pausar',resume:'Continuar',channelSettings:'Traducción e idioma',allLanguages:'Todos los idiomas compatibles están disponibles',inputLanguage:'Idioma del cliente',inputDevice:'Dispositivo de entrada',systemDefault:'Dispositivo predeterminado',customerSpeech:'Voz del cliente',japaneseText:'Texto japonés',japaneseReply:'Respuesta en japonés',customerTts:'Voz en idioma del cliente',speechMode:'Modo de reconocimiento',staffSpeech:'Personal habla · mantenga Space',staffSpeechActive:'Personal habla · japonés fijo',ttsOn:'TTS activado',ttsOff:'TTS desactivado',edgeNote:'Se usan voces neuronales en línea. No se requieren paquetes de voz de Windows.',output:'Salida de traducción',outputHint:'Muestra el original y el japonés',loadingTitle:'Preparando modelos locales',loadingBody:'La escucha comenzará cuando los modelos estén listos.',incoming:'Cliente · traducción japonesa',reply:'Personal · voz en idioma del cliente',clearHistory:'Borrar historial',historyCleared:'Historial borrado',correct:'Guardar corrección',correctSource:'Corrige el texto reconocido',correctTranslation:'Corrige la traducción',saved:'Corrección guardada localmente'}
};
let ui=localStorage.getItem('remoteplus-ui-language')||'ko',state={tts_enabled:true,paused:false,speech_mode:'customer'},retry=700,toastTimer,missingInput=0;
const t=key=>messages[ui]?.[key]||messages.en[key]||key;
function applyI18n(){document.documentElement.lang=ui;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));$('#ui-language').value=ui;applyState(state)}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),4200)}
function status(data){phase.textContent=data.message||data.phase||t('starting');$('.pulse').style.background=data.phase==='error'?'var(--red)':'var(--green)'}
function setPartner(code){$('#partner').textContent=names[code]||code?.toUpperCase()||'-'}
function selectValue(id,value){const el=$(id),wanted=String(value);if([...el.options].some(x=>x.value===wanted))el.value=wanted}
function add(item){const d=item.data||item;if(d.direction===undefined)return;empty?.remove();const el=document.createElement('article');el.className='entry '+(d.direction==='reply'?'reply':'incoming');const meta=document.createElement('div');meta.className='meta';const label=document.createElement('b');label.textContent=d.direction==='reply'?t('reply'):t('incoming');const tools=document.createElement('span');const timing=document.createElement('span');timing.textContent=d.latency_seconds?`${d.latency_seconds}s`:'';const correction=document.createElement('button');correction.className='correction';correction.textContent=t('correct');correction.onclick=()=>saveCorrection(d).catch(e=>toast(e.message));tools.append(timing,correction);meta.append(label,tools);const main=document.createElement('div');main.className='main';main.textContent=d.translated;const source=document.createElement('div');source.className='source';source.textContent=d.source;el.append(meta,main,source);feed.appendChild(el);while(feed.children.length>20)feed.removeChild(feed.firstChild);el.scrollIntoView({behavior:'smooth',block:'end'});if(d.source_language)setPartner(d.source_language)}
async function saveCorrection(d){const correctedSource=prompt(t('correctSource'),d.source);if(correctedSource===null)return;const correctedTranslation=prompt(t('correctTranslation'),d.translated);if(correctedTranslation===null)return;if(correctedSource===d.source&&correctedTranslation===d.translated)return;const r=await fetch('/api/feedback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({direction:d.direction,source_language:d.source_language,source:d.source,translation:d.translated,corrected_source:correctedSource===d.source?'':correctedSource,corrected_translation:correctedTranslation===d.translated?'':correctedTranslation})});if(!r.ok)throw Error((await r.json()).detail||'Unable to save correction');toast(t('saved'))}
function applyState(next){state={...state,...next};$('#tts').classList.toggle('on',!!state.tts_enabled);$('#tts').setAttribute('aria-pressed',!!state.tts_enabled);$('#tts em').textContent=state.tts_enabled?t('ttsOn'):t('ttsOff');$('#pause').textContent=state.paused?t('resume'):t('pause');if(state.input_language&&$('#language').options.length)selectValue('#language',state.input_language);if(state.input_device!==undefined&&$('#input-device').options.length)selectValue('#input-device',state.input_device);const staff=state.speech_mode==='staff',mode=$('#speech-mode');mode.classList.toggle('staff',staff);mode.setAttribute('aria-pressed',String(staff));mode.querySelector('em').textContent=staff?t('staffSpeechActive'):t('staffSpeech');if(state.input_language)setPartner(state.input_language)}
function renderLanguages(languages){const input=$('#language'),chosen=state.input_language;input.replaceChildren();for(const lang of languages){const op=document.createElement('option');op.value=lang.code;op.textContent=`${lang.native_name} · ${lang.name}`;input.appendChild(op)}selectValue('#language',chosen||input.options[0]?.value||'')}
async function loadDevices(){const r=await fetch('/api/devices');if(!r.ok)throw Error('Unable to load audio devices');const data=await r.json(),select=$('#input-device');while(select.options.length>1)select.remove(1);for(const item of data.inputs){const op=document.createElement('option');op.value=String(item.id);op.textContent=item.name;select.appendChild(op)}const selected=state.input_device,present=selected==='default'||[...select.options].some(x=>x.value===String(selected));missingInput=present?0:missingInput+1;if(!present&&missingInput>=2){missingInput=0;await control({input_device:'default'})}else applyState(state)}
function clearFeed(){feed.replaceChildren(empty);toast(t('historyCleared'))}
function snapshot(data){feed.replaceChildren(empty);applyState(data.state);status(data.state);renderLanguages(data.languages);for(const ev of data.history||[])if(ev.type==='translation')add(ev)}
async function control(body){const r=await fetch('/api/control',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error((await r.json()).detail||'Unable to change setting');const next=await r.json();applyState(next);return next}
$('#tts').onclick=()=>control({tts_enabled:!state.tts_enabled}).catch(e=>toast(e.message));$('#pause').onclick=()=>control({paused:!state.paused}).catch(e=>toast(e.message));$('#language').onchange=e=>control({active_language:e.target.value}).catch(e=>toast(e.message));$('#input-device').onchange=e=>{const value=e.target.value;control({input_device:value==='default'||value.startsWith('loopback:')?value:Number(value)}).catch(err=>toast(err.message))};
let spaceHeld=false,pointerHeld=false,modeRequestId=0;function setSpeechMode(mode){if(state.speech_mode===mode)return;const id=++modeRequestId;applyState({speech_mode:mode});control({speech_mode:mode}).then(next=>{if(id===modeRequestId)applyState(next)}).catch(error=>{if(id===modeRequestId){toast(error.message);applyState({speech_mode:'customer'})}})}function enterStaffMode(){setSpeechMode('staff')}function leaveStaffMode(){setSpeechMode('customer')}function isTypingTarget(target){return Boolean(target?.closest?.('input,textarea,select,[contenteditable="true"]'))}const staffButton=$('#speech-mode');staffButton.addEventListener('pointerdown',event=>{event.preventDefault();pointerHeld=true;staffButton.setPointerCapture?.(event.pointerId);enterStaffMode()});for(const name of ['pointerup','pointercancel','lostpointercapture'])staffButton.addEventListener(name,()=>{pointerHeld=false;if(!spaceHeld)leaveStaffMode()});staffButton.addEventListener('click',event=>event.preventDefault());window.addEventListener('keydown',event=>{if(event.code!=='Space'||event.repeat||spaceHeld||isTypingTarget(event.target))return;event.preventDefault();spaceHeld=true;enterStaffMode()});window.addEventListener('keyup',event=>{if(event.code!=='Space'||!spaceHeld)return;event.preventDefault();spaceHeld=false;if(!pointerHeld)leaveStaffMode()});window.addEventListener('blur',()=>{spaceHeld=false;pointerHeld=false;leaveStaffMode()});document.addEventListener('visibilitychange',()=>{if(document.hidden){spaceHeld=false;pointerHeld=false;leaveStaffMode()}});
$('#clear-history').onclick=()=>{if(confirm(t('clearHistory')+'?'))fetch('/api/history',{method:'DELETE'}).then(r=>{if(!r.ok)throw Error('Unable to clear history');clearFeed()}).catch(e=>toast(e.message))};$('#ui-language').onchange=e=>{ui=e.target.value;localStorage.setItem('remoteplus-ui-language',ui);applyI18n()};function connect(){const protocol=location.protocol==='https:'?'wss':'ws',ws=new WebSocket(`${protocol}://${location.host}/ws`);ws.onopen=()=>{$('#connection').classList.add('on');$('#connection span').textContent=t('connected');retry=700};ws.onclose=()=>{$('#connection').classList.remove('on');$('#connection span').textContent=t('reconnecting');setTimeout(connect,retry);retry=Math.min(retry*1.7,8000)};ws.onmessage=e=>{const event=JSON.parse(e.data);if(event.type==='snapshot')snapshot(event.data);else if(event.type==='translation')add(event);else if(event.type==='status')status(event.data);else if(event.type==='state')applyState(event.data);else if(event.type==='history_cleared')clearFeed();else if(event.type==='error'||event.type==='warning')toast(event.data.message)}}applyI18n();loadDevices().catch(error=>toast(error.message));setInterval(()=>loadDevices().catch(()=>{}),10000);connect();
