const $=s=>document.querySelector(s), feed=$('#feed'), empty=$('#empty'), phase=$('#phase strong');
const names={
  ja:'日本語',en:'English',ko:'한국어',zh:'中文',es:'Español',fr:'Français',de:'Deutsch',it:'Italiano',pt:'Português',ru:'Русский',
  ar:'العربية',hi:'हिन्दी',vi:'Tiếng Việt',th:'ไทย',id:'Bahasa Indonesia',ms:'Bahasa Melayu',tr:'Türkçe',nl:'Nederlands',pl:'Polski',uk:'Українська',cs:'Čeština',he:'עברית'
};
const messages={
  ko:{subtitle:'프런트 데스크 통역 콘솔',uiLanguage:'화면 언어',connecting:'연결 중',connected:'로컬 연결됨',reconnecting:'재연결 중',runtime:'실행 상태',starting:'시작 중',detectedLanguage:'현재 고객 언어',privacy:'동작 방식',processing:'최종 인식과 번역 우선 · 음성은 온라인',pause:'일시 정지',resume:'다시 시작',channelSettings:'현장 설정',allLanguages:'지원 언어 전체 사용 가능',inputLanguage:'고객 입력 언어',inputDevice:'음성 입력 장치',outputDevice:'음성 출력 장치',systemDefault:'시스템 기본 장치',customerSpeech:'고객 음성',japaneseText:'일본어 텍스트',japaneseReply:'일본어 답변',customerTts:'고객 언어 음성',speechMode:'인식 모드',staffSpeech:'직원 말하기 · Space 누르는 동안',staffSpeechActive:'직원 말하기 · 일본어 고정',ttsOn:'TTS 켜짐',ttsOff:'TTS 꺼짐',edgeNote:'큐가 밀리지 않도록 임시 자막 없이 최종 인식과 최신 발화를 우선 처리합니다.',output:'대화 기록',outputHint:'최신 발화 우선',loadingTitle:'시스템을 준비하고 있습니다',loadingBody:'준비가 끝나면 고객 음성을 듣기 시작합니다.',readyTitle:'시스템 준비 완료',readyBody:'음성을 기다리는 중입니다.',incoming:'고객 · 일본어 번역',reply:'직원 · 고객 언어 음성',replay:'다시 듣기',replayQueued:'다시 재생합니다',clearHistory:'기록 지우기',historyCleared:'화면 기록을 지웠습니다',correct:'교정 기록',correctSource:'인식된 원문을 수정하세요',correctTranslation:'번역문을 수정하세요',saved:'교정을 로컬에 저장했습니다',readingGuide:'읽기 보조',liveCaption:'실시간 인식 중',awaitingTranslation:'최종 인식 및 번역 준비 중',statusLoading:'모델 준비 중',statusListening:'시스템 준비 완료 · 듣는 중',statusRecognizing:'최종 음성 인식 중',statusTranslating:'번역 중',statusSpeaking:'번역 음성 재생 중',statusPaused:'일시 정지됨',statusWarning:'주의',statusError:'오류'},
  ja:{subtitle:'フロントデスク通訳コンソール',uiLanguage:'表示言語',connecting:'接続中',connected:'ローカル接続済み',reconnecting:'再接続中',runtime:'実行状態',starting:'起動中',detectedLanguage:'現在のお客様言語',privacy:'動作方式',processing:'最終認識と翻訳を優先・音声はオンライン',pause:'一時停止',resume:'再開',channelSettings:'現場設定',allLanguages:'対応言語をすべて選択可能',inputLanguage:'お客様の入力言語',inputDevice:'音声入力デバイス',outputDevice:'音声出力デバイス',systemDefault:'システム既定',customerSpeech:'お客様の音声',japaneseText:'日本語テキスト',japaneseReply:'日本語の返答',customerTts:'お客様言語の音声',speechMode:'認識モード',staffSpeech:'スタッフ発話・Spaceを押している間',staffSpeechActive:'スタッフ発話・日本語固定',ttsOn:'TTS オン',ttsOff:'TTS オフ',edgeNote:'キューが詰まらないよう、仮字幕なしで最終認識と最新発話を優先します。',output:'会話ログ',outputHint:'最新発話優先',loadingTitle:'システムを準備しています',loadingBody:'準備が完了するとお客様の音声を聞き始めます。',readyTitle:'システム準備完了',readyBody:'音声を待機しています。',incoming:'お客様・日本語訳',reply:'スタッフ・お客様言語音声',clearHistory:'履歴を消去',historyCleared:'表示履歴を消去しました',correct:'訂正を記録',correctSource:'認識された原文を修正してください',correctTranslation:'翻訳文を修正してください',saved:'訂正をローカルに保存しました',readingGuide:'読み方ガイド',liveCaption:'リアルタイム認識中',awaitingTranslation:'最終認識・翻訳を準備中',statusLoading:'モデルを準備中',statusListening:'システム準備完了・聞き取り中',statusRecognizing:'最終音声認識中',statusTranslating:'翻訳中',statusSpeaking:'翻訳音声を再生中',statusPaused:'一時停止中',statusWarning:'注意',statusError:'エラー'},
  en:{subtitle:'Front desk interpreting console',uiLanguage:'UI language',connecting:'Connecting',connected:'Local connection',reconnecting:'Reconnecting',runtime:'Runtime',starting:'Starting',detectedLanguage:'Customer language',privacy:'Mode',processing:'Final recognition first · voice online',pause:'Pause',resume:'Resume',channelSettings:'Field settings',allLanguages:'All supported languages are available',inputLanguage:'Customer input language',inputDevice:'Audio input device',outputDevice:'Audio output device',systemDefault:'System default',customerSpeech:'Customer speech',japaneseText:'Japanese text',japaneseReply:'Japanese reply',customerTts:'Customer-language audio',speechMode:'Recognition mode',staffSpeech:'Staff speaking · hold Space',staffSpeechActive:'Staff speaking · Japanese fixed',ttsOn:'TTS on',ttsOff:'TTS off',edgeNote:'No live captions: final recognition and the latest utterance are prioritized to prevent queues.',output:'Conversation log',outputHint:'Latest utterance first',loadingTitle:'Preparing the system',loadingBody:'Listening starts when the models are ready.',readyTitle:'System ready',readyBody:'Waiting for speech.',incoming:'Customer · Japanese translation',reply:'Staff · customer-language voice',clearHistory:'Clear history',historyCleared:'Display history cleared',correct:'Record correction',correctSource:'Correct the recognized text',correctTranslation:'Correct the translation',saved:'Correction saved locally',readingGuide:'Reading guide',liveCaption:'Live recognition',awaitingTranslation:'Preparing final recognition and translation',statusLoading:'Preparing models',statusListening:'System ready · Listening',statusRecognizing:'Final speech recognition',statusTranslating:'Translating',statusSpeaking:'Playing translated voice',statusPaused:'Paused',statusWarning:'Warning',statusError:'Error'},
  zh:{subtitle:'前台口译控制台',uiLanguage:'界面语言',connecting:'连接中',connected:'本地已连接',reconnecting:'正在重连',runtime:'运行状态',starting:'启动中',detectedLanguage:'当前客人语言',privacy:'运行方式',processing:'优先最终识别与翻译 · 语音在线',pause:'暂停',resume:'继续',channelSettings:'现场设置',allLanguages:'可直接选择所有支持的语言',inputLanguage:'客人输入语言',inputDevice:'音频输入设备',outputDevice:'音频输出设备',systemDefault:'系统默认设备',customerSpeech:'客人语音',japaneseText:'日语文本',japaneseReply:'日语回复',customerTts:'客人语言语音',speechMode:'识别模式',staffSpeech:'员工发言 · 按住 Space',staffSpeechActive:'员工发言 · 固定日语',ttsOn:'TTS 开启',ttsOff:'TTS 关闭',edgeNote:'为避免排队，不显示临时字幕，优先处理最终识别和最新语音。',output:'对话记录',outputHint:'最新语音优先',loadingTitle:'正在准备系统',loadingBody:'准备完成后开始接收客人语音。',readyTitle:'系统准备完成',readyBody:'正在等待语音。',incoming:'客人 · 日语翻译',reply:'员工 · 客人语言语音',clearHistory:'清除记录',historyCleared:'显示记录已清除',correct:'保存更正',correctSource:'请更正识别的文本',correctTranslation:'请更正译文',saved:'更正已保存在本机',readingGuide:'读音辅助',liveCaption:'实时识别中',awaitingTranslation:'正在准备最终识别和翻译',statusLoading:'正在准备模型',statusListening:'系统准备完成 · 正在聆听',statusRecognizing:'最终语音识别中',statusTranslating:'正在翻译',statusSpeaking:'正在播放译文语音',statusPaused:'已暂停',statusWarning:'警告',statusError:'错误'},
  es:{subtitle:'Consola de interpretación de recepción',uiLanguage:'Idioma de interfaz',connecting:'Conectando',connected:'Conexión local',reconnecting:'Reconectando',runtime:'Estado de ejecución',starting:'Iniciando',detectedLanguage:'Idioma del cliente',privacy:'Modo',processing:'Reconocimiento final primero · voz en línea',pause:'Pausar',resume:'Continuar',channelSettings:'Ajustes de campo',allLanguages:'Todos los idiomas compatibles están disponibles',inputLanguage:'Idioma del cliente',inputDevice:'Dispositivo de entrada',outputDevice:'Dispositivo de salida',systemDefault:'Dispositivo predeterminado',customerSpeech:'Voz del cliente',japaneseText:'Texto japonés',japaneseReply:'Respuesta en japonés',customerTts:'Voz en idioma del cliente',speechMode:'Modo de reconocimiento',staffSpeech:'Personal habla · mantenga Space',staffSpeechActive:'Personal habla · japonés fijo',ttsOn:'TTS activado',ttsOff:'TTS desactivado',edgeNote:'Sin subtítulos provisionales: se prioriza el reconocimiento final y la frase más reciente.',output:'Registro de conversación',outputHint:'Prioridad a la frase más reciente',loadingTitle:'Preparando el sistema',loadingBody:'La escucha comenzará cuando los modelos estén listos.',readyTitle:'Sistema listo',readyBody:'Esperando voz.',incoming:'Cliente · traducción japonesa',reply:'Personal · voz en idioma del cliente',clearHistory:'Borrar historial',historyCleared:'Historial borrado',correct:'Guardar corrección',correctSource:'Corrige el texto reconocido',correctTranslation:'Corrige la traducción',saved:'Corrección guardada localmente',readingGuide:'Guía de lectura',liveCaption:'Reconocimiento en vivo',awaitingTranslation:'Preparando reconocimiento y traducción finales',statusLoading:'Preparando modelos',statusListening:'Sistema listo · Escuchando',statusRecognizing:'Reconocimiento final',statusTranslating:'Traduciendo',statusSpeaking:'Reproduciendo voz traducida',statusPaused:'En pausa',statusWarning:'Aviso',statusError:'Error'}
};
const extraMessages={
  ko:{replay:'다시 듣기',replayQueued:'다시 재생합니다'},
  ja:{replay:'もう一度聞く',replayQueued:'もう一度再生します'},
  en:{replay:'Replay',replayQueued:'Replaying audio'},
  zh:{replay:'再次播放',replayQueued:'正在再次播放'},
  es:{replay:'Repetir audio',replayQueued:'Reproduciendo de nuevo'}
};
let ui=localStorage.getItem('remoteplus-ui-language')||'ko',state={tts_enabled:true,paused:false,speech_mode:'customer'},retry=700,toastTimer,missingInput=0;
const cards=new Map();
const t=key=>messages[ui]?.[key]||extraMessages[ui]?.[key]||messages.en[key]||extraMessages.en[key]||key;
const phaseKey={starting:'starting',loading:'statusLoading',ready:'statusListening',listening:'statusListening',recognizing:'statusRecognizing',translating:'statusTranslating',speaking:'statusSpeaking',paused:'statusPaused',warning:'statusWarning',error:'statusError'};
function applyI18n(){document.documentElement.lang=ui;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));$('#ui-language').value=ui;applyState(state);for(const card of cards.values()){const label=card.querySelector('.meta b');if(card.dataset.live==='1')label.textContent=t('liveCaption');else label.textContent=card.dataset.direction==='reply'?t('reply'):t('incoming');const replay=card.querySelector('.replay');if(replay)replay.textContent=t('replay');const correction=card.querySelector('.correction:not(.replay)');if(correction)correction.textContent=t('correct')}}

function updateEmptyState(){
  const card=$('#empty');
  if(!card)return;
  const ready=state.ready&&state.translator_ready&&!state.paused;
  const title=card.querySelector('h3'),body=card.querySelector('p');
  if(title)title.textContent=ready?t('readyTitle'):t('loadingTitle');
  if(body)body.textContent=ready?t('readyBody'):t('loadingBody');
}
function toast(message){if(!message)return;const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),4200)}
function status(data){const phaseName=(data?.ready&&data?.translator_ready&&['starting','loading','ready'].includes(data.phase))?'listening':data.phase;phase.textContent=t(phaseKey[phaseName]||'starting');$('.pulse').style.background=phaseName==='error'?'var(--red)':phaseName==='warning'?'#db9b3b':'var(--green)';updateEmptyState()}
function setPartner(code){$('#partner').textContent=names[code]||code?.toUpperCase()||'-'}
function selectValue(id,value){const el=$(id),wanted=String(value);if([...el.options].some(x=>x.value===wanted)){el.value=wanted;return true}return false}
function markUnavailable(select,value,label){if(value===undefined||value===null||String(value)==='default')return;const op=document.createElement('option');op.value=String(value);op.textContent=`${label} (${String(value)})`;op.disabled=true;select.appendChild(op);select.value=String(value)}
function scrollFeedBottom(){feed.scrollTop=feed.scrollHeight}
function makeCard(id,direction='incoming'){empty?.remove();const el=document.createElement('article');el.className='entry '+(direction==='reply'?'reply':'incoming');el.dataset.id=String(id);el.dataset.direction=direction;const meta=document.createElement('div');meta.className='meta';const label=document.createElement('b');const tools=document.createElement('span');const timing=document.createElement('span');timing.className='timing';const replay=document.createElement('button');replay.className='correction replay';replay.textContent=t('replay');replay.hidden=true;const correction=document.createElement('button');correction.className='correction';correction.textContent=t('correct');correction.hidden=true;tools.append(timing,replay,correction);meta.append(label,tools);const main=document.createElement('div');main.className='main';const source=document.createElement('div');source.className='source';const reading=document.createElement('div');reading.className='reading-guide';reading.hidden=true;el.append(meta,main,reading,source);feed.appendChild(el);cards.set(String(id),el);while(feed.children.length>20){const first=feed.firstChild;if(first?.dataset?.id)cards.delete(first.dataset.id);feed.removeChild(first)}return el}
function setCardTiming(el,value){el.querySelector('.timing').textContent=value||''}

const pronunciationCache=new Map();
const enWordKanaCache=new Map();
const koPhraseKana=new Map([
  ['감사합니다','カムサハムニダ'],['고맙습니다','コマプスムニダ'],['안녕하세요','アンニョンハセヨ'],['안녕히 가세요','アンニョンヒ ガセヨ'],['안녕히 계세요','アンニョンヒ ケセヨ'],
  ['죄송합니다','チェソンハムニダ'],['실례합니다','シルレハムニダ'],['잠시만 기다려 주세요','チャムシマン キダリョ ジュセヨ'],['기다려 주세요','キダリョ ジュセヨ'],
  ['확인해 보겠습니다','ファギネ ボゲッスムニダ'],['알겠습니다','アルゲッスムニダ'],['네','ネ'],['아니요','アニヨ'],['괜찮습니다','ケンチャンスムニダ'],
  ['여기입니다','ヨギイムニダ'],['이쪽입니다','イッチョギムニダ'],['예약 확인 도와드리겠습니다','イェヤク ファギン トワドゥリゲッスムニダ']
]);
const enPhraseKana=new Map([
  ['thank you','サンキュー'],['thank you very much','サンキュー ベリー マッチ'],['please wait','プリーズ ウェイト'],['please wait a moment','プリーズ ウェイト ア モーメント'],
  ['one moment please','ワン モーメント プリーズ'],['just a moment please','ジャスト ア モーメント プリーズ'],['i will check','アイ ウィル チェック'],
  ['i will check your reservation','アイ ウィル チェック ユア レザベーション'],['please show me your passport','プリーズ ショウ ミー ユア パスポート'],
  ['welcome','ウェルカム'],['you are welcome','ユー アー ウェルカム'],['sorry','ソーリー'],['excuse me','エクスキューズ ミー'],['yes','イエス'],['no','ノー']
]);
const enWordKana={
  i:'アイ',we:'ウィー',you:'ユー',your:'ユア',me:'ミー',my:'マイ',our:'アワー',the:'ザ',a:'ア',an:'アン',to:'トゥ',for:'フォー',of:'オブ',in:'イン',on:'オン',at:'アット',
  is:'イズ',are:'アー',am:'アム',be:'ビー',can:'キャン',could:'クッド',will:'ウィル',would:'ウッド',may:'メイ',please:'プリーズ',wait:'ウェイト',moment:'モーメント',just:'ジャスト',
  thank:'サンク',thanks:'サンクス',welcome:'ウェルカム',sorry:'ソーリー',excuse:'エクスキューズ',yes:'イエス',no:'ノー',ok:'オーケー',okay:'オーケー',
  check:'チェック',reservation:'レザベーション',booking:'ブッキング',passport:'パスポート',name:'ネーム',room:'ルーム',key:'キー',card:'カード',breakfast:'ブレックファスト',
  lobby:'ロビー',front:'フロント',desk:'デスク',elevator:'エレベーター',towel:'タオル',water:'ウォーター',receipt:'レシート',payment:'ペイメント',cash:'キャッシュ',credit:'クレジット',
  here:'ヒア',there:'ゼア',this:'ディス',that:'ザット',today:'トゥデイ',tomorrow:'トゥモロー',tonight:'トゥナイト',morning:'モーニング',evening:'イブニング',
  available:'アベイラブル',minutes:'ミニッツ',minute:'ミニット',hour:'アワー',hours:'アワーズ',taxi:'タクシー',shuttle:'シャトル',airport:'エアポート',restaurant:'レストラン'
};
function kataForHangulSyllable(ch){const code=ch.charCodeAt(0)-0xAC00;if(code<0||code>11171)return '';const L=Math.floor(code/588),V=Math.floor((code%588)/28),T=code%28;const vowel=['a','ae','ya','yae','eo','e','yeo','ye','o','wa','wae','oe','yo','u','wo','we','wi','yu','eu','ui','i'][V];const cons=['g','kk','n','d','tt','r','m','b','pp','s','ss','','j','jj','ch','k','t','p','h'][L];const final=['','k','k','ks','n','nj','nh','t','l','lk','lm','lb','ls','lt','lp','lh','m','p','ps','t','t','ng','t','t','k','t','p','t'][T];const rows={
  '':{a:'ア',ae:'エ',ya:'ヤ',yae:'イェ',eo:'オ',e:'エ',yeo:'ヨ',ye:'イェ',o:'オ',wa:'ワ',wae:'ウェ',oe:'ウェ',yo:'ヨ',u:'ウ',wo:'ウォ',we:'ウェ',wi:'ウィ',yu:'ユ',eu:'ウ',ui:'ウィ',i:'イ'},
  g:{a:'ガ',ae:'ゲ',ya:'ギャ',yae:'ギェ',eo:'ゴ',e:'ゲ',yeo:'ギョ',ye:'ギェ',o:'ゴ',wa:'グァ',wae:'グェ',oe:'グェ',yo:'ギョ',u:'グ',wo:'グォ',we:'グェ',wi:'グィ',yu:'ギュ',eu:'グ',ui:'グィ',i:'ギ'},
  kk:{a:'カ',ae:'ケ',ya:'キャ',yae:'キェ',eo:'コ',e:'ケ',yeo:'キョ',ye:'キェ',o:'コ',u:'ク',yo:'キョ',yu:'キュ',eu:'ク',i:'キ'},
  n:{a:'ナ',ae:'ネ',ya:'ニャ',eo:'ノ',e:'ネ',yeo:'ニョ',o:'ノ',yo:'ニョ',u:'ヌ',yu:'ニュ',eu:'ヌ',i:'ニ'},
  d:{a:'ダ',ae:'デ',ya:'ディャ',eo:'ド',e:'デ',yeo:'ディョ',o:'ド',yo:'ディョ',u:'ドゥ',yu:'デュ',eu:'ドゥ',i:'ディ'},
  tt:{a:'タ',ae:'テ',ya:'ティャ',eo:'ト',e:'テ',o:'ト',u:'トゥ',eu:'トゥ',i:'ティ'},
  r:{a:'ラ',ae:'レ',ya:'リャ',eo:'ロ',e:'レ',yeo:'リョ',o:'ロ',yo:'リョ',u:'ル',yu:'リュ',eu:'ル',i:'リ'},
  m:{a:'マ',ae:'メ',ya:'ミャ',eo:'モ',e:'メ',yeo:'ミョ',o:'モ',yo:'ミョ',u:'ム',yu:'ミュ',eu:'ム',i:'ミ'},
  b:{a:'バ',ae:'ベ',ya:'ビャ',eo:'ボ',e:'ベ',yeo:'ビョ',o:'ボ',yo:'ビョ',u:'ブ',yu:'ビュ',eu:'ブ',i:'ビ'},
  pp:{a:'パ',ae:'ペ',eo:'ポ',e:'ペ',o:'ポ',u:'プ',eu:'プ',i:'ピ'},
  s:{a:'サ',ae:'セ',ya:'シャ',eo:'ソ',e:'セ',yeo:'ショ',o:'ソ',yo:'ショ',u:'ス',yu:'シュ',eu:'ス',i:'シ'},
  ss:{a:'サ',ae:'セ',eo:'ソ',e:'セ',o:'ソ',u:'ス',eu:'ス',i:'シ'},
  j:{a:'ジャ',ae:'ジェ',ya:'ジャ',eo:'ジョ',e:'ジェ',yeo:'ジョ',o:'ジョ',yo:'ジョ',u:'ジュ',yu:'ジュ',eu:'ジュ',i:'ジ'},
  jj:{a:'チャ',ae:'チェ',eo:'チョ',e:'チェ',o:'チョ',u:'チュ',eu:'チュ',i:'チ'},
  ch:{a:'チャ',ae:'チェ',ya:'チャ',eo:'チョ',e:'チェ',yeo:'チョ',o:'チョ',yo:'チョ',u:'チュ',yu:'チュ',eu:'チュ',i:'チ'},
  k:{a:'カ',ae:'ケ',ya:'キャ',eo:'コ',e:'ケ',yeo:'キョ',o:'コ',yo:'キョ',u:'ク',yu:'キュ',eu:'ク',i:'キ'},
  t:{a:'タ',ae:'テ',eo:'ト',e:'テ',o:'ト',u:'トゥ',eu:'トゥ',i:'ティ'},
  p:{a:'パ',ae:'ペ',eo:'ポ',e:'ペ',o:'ポ',u:'プ',yu:'ピュ',eu:'プ',i:'ピ'},
  h:{a:'ハ',ae:'ヘ',ya:'ヒャ',eo:'ホ',e:'ヘ',yeo:'ヒョ',o:'ホ',yo:'ヒョ',u:'フ',yu:'ヒュ',eu:'フ',i:'ヒ'}
};const end={k:'ク',ks:'ク',n:'ン',nj:'ン',nh:'ン',t:'ッ',l:'ル',lk:'ルク',lm:'ルム',lb:'ルプ',ls:'ル',lt:'ル',lp:'ルプ',lh:'ル',m:'ム',p:'プ',ps:'プ',ng:'ン'};return (rows[cons]?.[vowel]||rows[cons]?.a||'')+(end[final]||'')}
function koKanaWord(word){if(koPhraseKana.has(word))return koPhraseKana.get(word);let out='';for(const ch of word)out+=kataForHangulSyllable(ch)||ch;return out!==word?out:''}
const enFallbackKanaChunks=[
  ['under','アンダー'],['stand','スタンド'],['tion','ション'],['sion','ジョン'],['ture','チャー'],['sure','シャー'],['ough','オー'],['augh','オー'],['eigh','エイ'],['igh','アイ'],['air','エア'],['ear','イア'],['our','アワー'],['ow','アウ'],['ou','アウ'],['oo','ウー'],['ee','イー'],['ea','イー'],['ai','エイ'],['ay','エイ'],['oa','オウ'],['oi','オイ'],['oy','オイ'],['ch','チ'],['sh','シ'],['th','ス'],['ph','フ'],['wh','ウ'],['ck','ック'],['ng','ング'],['qu','ク'],['st','スト'],['str','ストゥル'],['tr','トゥル'],['dr','ドゥル'],['cl','クル'],['cr','クル'],['gr','グル'],['pr','プル'],['br','ブル'],['fr','フル'],['pl','プル'],['bl','ブル'],['fl','フル'],['sl','スル'],['sm','スム'],['sn','スン'],['sp','スプ'],['sk','スク'],['sw','スウ'],['er','アー'],['or','オー'],['ar','アー'],['ir','アー'],['ur','アー'],['al','アル'],['le','ル'],['ce','ス'],['ci','シ'],['cy','シ'],['ge','ジ'],['gi','ジ'],['gy','ジ'],['kn','ナ'],['wr','ラ'],['mb','ム']
];
const enFallbackKanaLetters={a:'ア',b:'ブ',c:'ク',d:'ド',e:'エ',f:'フ',g:'グ',h:'ハ',i:'イ',j:'ジ',k:'ク',l:'ル',m:'ム',n:'ン',o:'オ',p:'プ',q:'ク',r:'ル',s:'ス',t:'ト',u:'ア',v:'ヴ',w:'ウ',x:'クス',y:'イ',z:'ズ'};
const enFallbackKanaByFirst=enFallbackKanaChunks.reduce((acc,item)=>{const first=item[0][0];(acc[first]||=[]).push(item);return acc},{});
for(const items of Object.values(enFallbackKanaByFirst))items.sort((a,b)=>b[0].length-a[0].length);
function enFallbackKanaWord(key){let out='',i=0;while(i<key.length){let hit=null;for(const item of enFallbackKanaByFirst[key[i]]||[]){if(key.startsWith(item[0],i)){hit=item;break}}if(hit){out+=hit[1];i+=hit[0].length}else{out+=enFallbackKanaLetters[key[i]]||key[i].toUpperCase();i++}}return out}
function enKanaWord(word){const key=word.toLowerCase().replace(/^'+|'+$/g,'');if(!key)return '';const cached=enWordKanaCache.get(key);if(cached)return cached;let kana=enWordKana[key]||'';if(!kana){if(key.endsWith('tion'))kana=word.slice(0,-4).toUpperCase()+'ション';else if(key.endsWith('sion'))kana=word.slice(0,-4).toUpperCase()+'ジョン';else kana=enFallbackKanaWord(key)}enWordKanaCache.set(key,kana);return kana}
function makeReadingToken(text,kind='plain'){const span=document.createElement('span');span.className='reading-token reading-'+kind;span.textContent=text;return span}
function makeRuby(original,kana){const ruby=document.createElement('ruby');ruby.className='reading-ruby';const base=document.createElement('rb');base.className='reading-base';base.textContent=original;const rt=document.createElement('rt');rt.className='reading-kana';rt.textContent=kana;ruby.append(base,rt);return ruby}
function readingTokenKind(token){if(!token.trim())return 'space';return /[A-Za-z가-힣]/.test(token)?'plain':'punctuation'}
function renderReadingGuide(el,text,lang){const box=el.querySelector('.reading-guide');if(!box)return;box.hidden=true;box.replaceChildren();if(el.dataset.direction!=='reply'||!['ko','en'].includes(lang)||!text||text.length>180)return;const key=lang+'|'+text;let cached=pronunciationCache.get(key);if(!cached){const exact=(lang==='ko'?koPhraseKana:enPhraseKana).get(text.trim().toLowerCase())||(lang==='ko'?koPhraseKana:enPhraseKana).get(text.trim());cached={exact,parts:null};if(!exact){const tokenRe=lang==='ko'?/[가-힣]+|[^가-힣]+/g:/[A-Za-z']+|[^A-Za-z']+/g;cached.parts=[...text.matchAll(tokenRe)].map(m=>{const tok=m[0],kana=lang==='ko'&&/[가-힣]/.test(tok)?koKanaWord(tok):lang==='en'&&/[A-Za-z]/.test(tok)?enKanaWord(tok):'';return [tok,kana]})}pronunciationCache.set(key,cached)}const label=document.createElement('span');label.className='reading-label';label.textContent=t('readingGuide')+': ';box.appendChild(label);if(cached.exact){box.appendChild(makeRuby(text,cached.exact))}else{let useful=false;for(const [tok,kana] of cached.parts){if(kana){useful=true;box.appendChild(makeRuby(tok,kana))}else box.appendChild(makeReadingToken(tok,readingTokenKind(tok)))}if(!useful){box.replaceChildren();box.hidden=true;return}}box.hidden=false}
function scheduleReadingGuide(el,d){const lang=d.target_language||state.input_language;if(d.direction!=='reply'||!['ko','en'].includes(lang))return;const run=()=>{if(el.dataset.final==='1')renderReadingGuide(el,d.translated||'',lang)};(window.requestIdleCallback||window.setTimeout)(run,{timeout:800})}
function preview(item){const d=item.data||item;if(!d.text)return;const id=String(d.utterance_id);let el=cards.get(id);if(!el)el=makeCard(id,d.speech_mode==='staff'?'reply':'incoming');if(el.dataset.final==='1')return;el.classList.add('live');el.dataset.live='1';el.querySelector('.meta b').textContent=t('liveCaption');el.querySelector('.main').textContent=t('awaitingTranslation');el.querySelector('.source').textContent=d.text;setCardTiming(el,'LIVE');if(d.language)setPartner(d.language);scrollFeedBottom()}
function discardPreview(item){const d=item.data||item,id=String(d.utterance_id),el=cards.get(id);if(el&&el.dataset.final!=='1'){cards.delete(id);el.remove()}}
function add(item){const d=item.data||item;if(d.direction===undefined)return;const id=String(d.utterance_id||`final-${Date.now()}-${Math.random()}`);let el=cards.get(id);if(!el)el=makeCard(id,d.direction);el.className='entry '+(d.direction==='reply'?'reply':'incoming');el.dataset.direction=d.direction;el.dataset.final='1';el.dataset.live='0';el.querySelector('.meta b').textContent=d.direction==='reply'?t('reply'):t('incoming');setCardTiming(el,d.latency_seconds?`${d.latency_seconds}s`:'');el.querySelector('.main').textContent=d.translated;el.querySelector('.source').textContent=d.source;const reading=el.querySelector('.reading-guide');if(reading){reading.hidden=true;reading.replaceChildren()}scheduleReadingGuide(el,d);const replay=el.querySelector('.replay');replay.hidden=d.direction!=='reply';replay.onclick=()=>replayTts(d).catch(e=>toast(e.message));const correction=el.querySelector('.correction:not(.replay)');correction.hidden=false;correction.onclick=()=>saveCorrection(d).catch(e=>toast(e.message));if(d.source_language)setPartner(d.source_language);scrollFeedBottom()}
async function replayTts(d){const r=await fetch('/api/replay',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:d.translated,language:d.target_language})});if(!r.ok)throw Error((await r.json()).detail||'Could not replay audio');toast(t('replayQueued'))}
async function saveCorrection(d){const correctedSource=prompt(t('correctSource'),d.source);if(correctedSource===null)return;const correctedTranslation=prompt(t('correctTranslation'),d.translated);if(correctedTranslation===null)return;if(correctedSource===d.source&&correctedTranslation===d.translated)return;const r=await fetch('/api/feedback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({direction:d.direction,source_language:d.source_language,source:d.source,translation:d.translated,corrected_source:correctedSource===d.source?'':correctedSource,corrected_translation:correctedTranslation===d.translated?'':correctedTranslation})});if(!r.ok)throw Error((await r.json()).detail||'Unable to save correction');toast(t('saved'))}
function applyState(next){state={...state,...next};if(state.ready&&state.translator_ready&&['starting','loading','ready'].includes(state.phase))state.phase='listening';$('#tts').classList.toggle('on',!!state.tts_enabled);$('#tts').setAttribute('aria-pressed',!!state.tts_enabled);$('#tts em').textContent=state.tts_enabled?t('ttsOn'):t('ttsOff');$('#pause').textContent=state.paused?t('resume'):t('pause');if(state.input_language&&$('#language').options.length)selectValue('#language',state.input_language);if(state.input_device!==undefined&&$('#input-device').options.length)selectValue('#input-device',state.input_device);if(state.output_device!==undefined&&$('#output-device').options.length)selectValue('#output-device',state.output_device);const staff=state.speech_mode==='staff',mode=$('#speech-mode');mode.classList.toggle('staff',staff);mode.setAttribute('aria-pressed',String(staff));mode.querySelector('em').textContent=staff?t('staffSpeechActive'):t('staffSpeech');if(state.input_language)setPartner(state.input_language);updateEmptyState()}
function renderLanguages(languages){const input=$('#language'),chosen=state.input_language;input.replaceChildren();for(const lang of languages){const op=document.createElement('option');op.value=lang.code;op.textContent=`${lang.native_name} (${lang.name})`;input.appendChild(op)}selectValue('#language',chosen)}
async function loadDevices(){const r=await fetch('/api/devices');if(!r.ok)throw Error((await r.json()).detail||'Could not load devices');const d=await r.json(),input=$('#input-device'),output=$('#output-device'),chosenInput=state.input_device,chosenOutput=state.output_device;for(const [select,items,chosen] of [[input,d.inputs||[],chosenInput],[output,d.outputs||[],chosenOutput]]){select.replaceChildren();const def=document.createElement('option');def.value='default';def.textContent=t('systemDefault');select.appendChild(def);for(const item of items){const op=document.createElement('option');op.value=item.id;op.textContent=item.name;select.appendChild(op)}if(!selectValue('#'+select.id,chosen))markUnavailable(select,chosen,'Unavailable')}if(d.warnings?.length&&!missingInput++){toast(d.warnings[0])}}
async function control(payload){const r=await fetch('/api/control',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw Error((await r.json()).detail||'Control update failed');applyState(await r.json())}
function clearFeed(){cards.clear();feed.replaceChildren(empty)}
function snapshot(data){clearFeed();applyState(data.state);status(data.state);renderLanguages(data.languages);for(const ev of data.history||[])if(ev.type==='translation')add(ev)}
$('#language').onchange=e=>control({active_language:e.target.value}).catch(err=>toast(err.message));$('#input-device').onchange=e=>control({input_device:e.target.value}).catch(err=>toast(err.message));$('#output-device').onchange=e=>control({output_device:e.target.value}).catch(err=>toast(err.message));$('#tts').onclick=()=>control({tts_enabled:!state.tts_enabled}).catch(err=>toast(err.message));$('#pause').onclick=()=>control({paused:!state.paused}).catch(err=>toast(err.message));
function setStaff(active){if((state.speech_mode==='staff')===active)return;control({speech_mode:active?'staff':'customer'}).catch(err=>toast(err.message))}
const mode=$('#speech-mode');mode.addEventListener('pointerdown',e=>{e.preventDefault();setStaff(true)});for(const event of ['pointerup','pointercancel','pointerleave'])mode.addEventListener(event,()=>setStaff(false));window.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&document.activeElement?.tagName!=='SELECT'){e.preventDefault();setStaff(true)}});window.addEventListener('keyup',e=>{if(e.code==='Space'){e.preventDefault();setStaff(false)}});window.addEventListener('blur',()=>setStaff(false));
$('#clear-history').onclick=()=>{if(confirm(t('clearHistory')+'?'))fetch('/api/history',{method:'DELETE'}).then(r=>{if(!r.ok)throw Error('Unable to clear history');clearFeed()}).catch(e=>toast(e.message))};$('#ui-language').onchange=e=>{ui=e.target.value;localStorage.setItem('remoteplus-ui-language',ui);applyI18n()};
function connect(){const protocol=location.protocol==='https:'?'wss':'ws',ws=new WebSocket(`${protocol}://${location.host}/ws`);ws.onopen=()=>{$('#connection').classList.add('on');$('#connection span').textContent=t('connected');retry=700};ws.onclose=()=>{$('#connection').classList.remove('on');$('#connection span').textContent=t('reconnecting');setTimeout(connect,retry);retry=Math.min(retry*1.7,8000)};ws.onmessage=e=>{const event=JSON.parse(e.data);if(event.type==='snapshot')snapshot(event.data);else if(event.type==='preview')preview(event);else if(event.type==='preview_discard')discardPreview(event);else if(event.type==='translation')add(event);else if(event.type==='status')status(event.data);else if(event.type==='state')applyState(event.data);else if(event.type==='history_cleared')clearFeed();else if(event.type==='error'||event.type==='warning')toast(event.data.message)}}
applyI18n();loadDevices().catch(error=>toast(error.message));setInterval(()=>loadDevices().catch(()=>{}),60000);connect();
